refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
  log-error:
    kind: file
    path: "log/log-error.log"
    encoder:
      pattern: "{d} - {m}{n}"

root:
  level: debug
  appenders:
    - stdout

loggers:
  app:
    level: warn
    appenders:
      - log-error
    additive: false